export {default as Home} from './Home.jsx'
export {default as Login} from './Login.jsx'
export {default as Product} from './Product.jsx'
export {default as Products} from './Products.jsx'
export {default as SignUp} from './SignUp.jsx'
export {default as NotFound} from './NotFound.jsx'